# Built with Jekyll 3.2.0

title:               Sempiterna Serendipia
tagline:             ''
description:         'Procrastinación Perceptiva'
url:                 https://santi-gf.github.io
baseurl:             ''

author:
  name:              Santi
  url:               https://santi-gf.github.io
  # email:             santi@miservidor.es

permalink: pretty
permalink: /:title/

encoding: utf-8

markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  style: compressed # Minify css

plugins:
  - jekyll-last-modified-at

